; ==============================
; BAR INTERNA (LAPTOP - ARRIBA)
; ==============================
[bar/main-internal]
monitor = eDP-1
width = 100%
height = 28
bottom = false

background = #1f1f28
foreground = #dcd7ba

padding-left = 1
padding-right = 1
module-margin = 1

separator = "|"
separator-foreground = #727169

font-0 = "IosevkaTerm Nerd Font Mono:size=11"
font-1 = "IosevkaTerm Nerd Font:size=11"

modules-left = i3
modules-center = xwindow
modules-right = battery date


[bar/main-external]
monitor = HDMI-1
width = 100%
height = 28
bottom = false

background = #1f1f28
foreground = #dcd7ba

padding-left = 1
padding-right = 1
module-margin = 1

separator = "|"
separator-foreground = #727169

font-0 = "IosevkaTerm Nerd Font Mono:size=11"
font-1 = "IosevkaTerm Nerd Font:size=11"

modules-left = i3
modules-center = xwindow
modules-right = network battery date

; ==============================
; WORKSPACES (FIX)
; ==============================
[module/i3]
type = internal/i3

index-sort = true
strip-wsnumbers = false

format = <label-state>

label-focused = %name%
label-focused-background = #7e9cd8
label-focused-foreground = #1f1f28
label-focused-padding = 2

label-unfocused = %name%
label-unfocused-foreground = #727169
label-unfocused-padding = 2

label-visible = %name%
label-visible-foreground = #e6c384
label-visible-padding = 2

label-urgent = %name%
label-urgent-background = #e46876
label-urgent-foreground = #1f1f28
label-urgent-padding = 2

; ------------------------------
; VENTANA ACTIVA
; ------------------------------
[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%
label-foreground = #98bb6c

; ------------------------------
; RED
; ------------------------------
[module/network]
type = internal/network
interface = wlp1s0
interval = 3

format-connected = <label-connected>
format-disconnected = <label-disconnected>

label-connected =   %essid% (%signal%%) ↓%downspeed%
label-disconnected = 󰤮  Offline

; ------------------------------
; BATERÍA
; ------------------------------
[module/battery]
type = internal/battery

battery = BAT0
adapter = AC

poll-interval = 5

format-charging =  <label-charging>
format-discharging = <ramp-capacity> <label-discharging>
format-full =   100%

label-charging = %percentage%%
label-discharging = %percentage%%
label-full = 100%

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 

; ------------------------------
; FECHA
; ------------------------------
[module/date]
type = internal/date
interval = 5
date = %H:%M  %d %B %Y
label = 󰃰  %date%
